jenkins:
  securityRealm:
    local:
      allowsSignup: false
      users:
       - id: "admin"
         password: "password123"
  authorizationStrategy:
    globalMatrix:
      permissions:
        - "Overall/Administer:admin"
credentials:
  system:
    domainCredentials:
      - credentials:
          - basicSSHUserPrivateKey:
              scope: GLOBAL
              id: "github-ssh-key"
              username: "git"
              privateKeySource:
                directEntry:
                  privateKey: "${readFile:/var/lib/jenkins/.ssh/id_rsa}"
jobs:
  - script: >
      multibranchPipelineJob('Node-App-CI-CD') {
        branchSources {
          github {
            id('node-app-repo')
            scanCredentialsId('github-ssh-key')
            repoOwner('hkaibara')
            repository('cynapse-init')
            buildOriginBranch(true)
            buildOriginPRMerge(true)
            buildOriginPRHead(true)
          }
        }
        orphanedItemStrategy {
          discardOldItems { 
            numToKeep(10) 
          }
        }
      }
